//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortingWordsByLetters.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortingWordsByLetters.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem, ipsum, dolor, sit, amet, consectetur, adipiscing, elit., Proin, rhoncus, augue, ut, volutpat, hendrerit., Praesent, odio, justo, faucibus, eget, consequat, ac, finibus, eu, augue., Aliquam, et, cursus, erat., Nulla, mattis, dignissim, nisl, quis, bibendum, massa, egestas, sit, amet., Maecenas, et, vehicula, tortor., Ut, in, dui, vitae, risus, gravida, cursus, non, commodo, turpis., Nullam, pulvinar, orci, non, luctus, vulputate., Etiam, sed, cursus, diam, vitae, accumsan, nulla.
        ///
        ///Sed, in, dapibus,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigString {
            get {
                return ResourceManager.GetString("BigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to malesuada.
        ///
        ///Donec, pulvinar.
        ///
        ///Maecenas, mauris.
        ///
        ///Maecenas, volutpat.
        ///
        ///Maecenas, lacus.
        ///
        ///Aenean, arcu.
        ///
        ///Aenean, placerat.
        ///
        ///Vivamus, diam.
        ///
        ///Aliquam, venenatis.
        ///
        ///Aenean, quam.
        ///
        ///Aenean, pharetra.
        ///
        ///Vivamus, magna.
        ///
        ///Nulla, pulvinar.
        ///
        ///Aliquam, mauris.
        ///
        ///Aliquam, quam.
        ///
        ///Aliquam, quam.
        ///
        ///Aliquam, ornare.
        ///
        ///Curabitur, faucibus.
        ///
        ///Nullam, dapibus.
        ///
        ///Mauris, magna.
        ///
        ///Vestibulum, arcu.
        ///
        ///Cras, condimentum.
        ///
        ///Aliquam, egestas.
        ///
        ///Cras, facilisi.
        ///
        ///Phasellus, placerat.
        ///
        ///In, lacus.
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedBigString {
            get {
                return ResourceManager.GetString("ExpectedBigString", resourceCulture);
            }
        }
    }
}
